---
-  name: CentOS Setup Yum Repo
   ansible.builtin.yum:
     name: epel-release
     state: present
     update_cache: yes
   become: yes

- name: CentOS Git Install
  ansible.builtin.yum:
    name:
      - git
    state: latest
  become: yes
