---
- name: playbook testing with git install
  hosts: webservers
  gather_facts: no
  remote_user: student
  vars:
    root_dir: /usr/share/nginx/html
    nginx_port: 80

  tasks:
  - name: install git
    ansible.builtin.apt:
      name: git
      state: present
      update_cache: yes
    become: yes
    tags:
    - install

  - name: install nginx
    ansible.builtin.apt:
      name: nginx
      state: latest
      update_cache: yes
    become: yes
    tags:
    - install

  - name: update nginx config
    ansible.builtin.template:
      src: ../files/templates/nginx.conf.j2
      dest: /etc/nginx/nginx.conf
    notify:
    - restart nginx
    tags:
    - update_config
    become: yes

  - name: copy src files
    ansible.builtin.template:
      src: ../files/index.html.j2
      dest: "{{root_dir}}/index.html"
    tags:
    - page_update
    become: yes

  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
    become: yes

  handlers:
  - name: restart nginx
    ansible.builtin.service:
      name: nginx
      state: reloaded
      enabled: yes
    become: yes






