---
- name: create users
  hosts: servers
  gather_facts: no
  remote_user: student
  vars:
    users:
      - jamie
      - sansa
      - robert

  tasks:
    - name: add users
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
        generate_ssh_key: yes
      loop: "{{ users }}"
      become: yes

    - name: apply gitconfig
      ansible.builtin.template:
        src: ../files/templates/gitconfig.j2
        dest: "/home/{{ item }}/.gitconfig"
      loop: "{{ users }}"
      become: yes

    - name: apply keys
      ansible.builtin.copy:
        src: ../files/id_ed25519.pub
        dest: "/home/{{ item }}/.ssh/authorized_keys"
      loop: "{{ users }}"
      become: yes
